name: saubhagya
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2+1
  cupertino_icons: ^1.0.0
  url_launcher: ^6.0.3

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/app/ios_app_icon.png"
  image_path_android: "assets/app/app_icon_bg.png"
  adaptive_icon_background: "assets/app/app_icon_bg.png"
  adaptive_icon_foreground: "assets/app/app_icon_fg.png"




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/profile/
    - assets/common/

  fonts:
    - family: ComicNeue
      fonts:
        - asset: assets/fonts/Comic_Neue/ComicNeue-Bold.ttf
        - asset: assets/fonts/Comic_Neue/ComicNeue-BoldItalic.ttf
        - asset: assets/fonts/Comic_Neue/ComicNeue-Italic.ttf
        - asset: assets/fonts/Comic_Neue/ComicNeue-Light.ttf
        - asset: assets/fonts/Comic_Neue/ComicNeue-LightItalic.ttf
        - asset: assets/fonts/Comic_Neue/ComicNeue-Regular.ttf